# 2D NumPy Array

In [1]:
# Creating a 2D Array
import numpy as np

data = np.array([
    [10, 20, 30],
    [20, 40, 60],
    [30, 50, 90],
    [40, 60, 120]
])

print(data)

[[ 10  20  30]
 [ 20  40  60]
 [ 30  50  90]
 [ 40  60 120]]


In [2]:
# Calculating the mean of each row
import numpy as np

data = np.array([
    [10, 20, 30],
    [20, 40, 60],
    [30, 50, 90],
    [40, 60, 120]
])

print(data)

[[ 10  20  30]
 [ 20  40  60]
 [ 30  50  90]
 [ 40  60 120]]


In [4]:
# Calucalting the maximum value of each column
import numpy as np

column_maxima = data.max(axis=0)

print("Column maxima:", column_maxima)

Column maxima: [ 40  60 120]


# Normalize each column to 0–1

In [6]:
# Normalizing the data of each column in the range of 0 to 1
column_min = data.min(axis=0)
column_max = data.max(axis=0)

normalized_data = (data - column_min) / (column_max - column_min)
print(data)
print("Normalized data:")
print(normalized_data)

[[ 10  20  30]
 [ 20  40  60]
 [ 30  50  90]
 [ 40  60 120]]
Normalized data:
[[0.         0.         0.        ]
 [0.33333333 0.5        0.33333333]
 [0.66666667 0.75       0.66666667]
 [1.         1.         1.        ]]


# Broadcasting

In [8]:
# Broadcasting allows NumPy to perform operations between arrays of compatible shapes without explicitly repeating the smaller array.
column_means = data.mean(axis=0)

print("Column means:", column_means)

centered_data = data - column_means

print("Centered data:")
print(centered_data)

Column means: [25.  42.5 75. ]
Centered data:
[[-15.  -22.5 -45. ]
 [ -5.   -2.5 -15. ]
 [  5.    7.5  15. ]
 [ 15.   17.5  45. ]]


# Vectorization

In [9]:
# Creating a large Array
import numpy as np
import time

data = np.random.rand(1000000)

In [10]:
# Calculating the time of processing each element with loop
start = time.time()

loop_result = []

for value in data:
    loop_result.append(value * 2)

loop_time = time.time() - start

print("Loop time:", loop_time)

Loop time: 0.24386072158813477


In [11]:
# With Vectorized numpy operation
start = time.time()

vectorized_result = data * 2

vectorized_time = time.time() - start

print("Vectorized time:", vectorized_time)

Vectorized time: 0.12277626991271973
